### ISSUE TITLE
After install doesn't work

### ISSUE THREAD

**Issue by kxxxo** [rafaelvaloto/yii2-material-design-lite#1]
Throw exception: 
The file or directory to be published does not exist: {...}\vendor/bower/bower-asset/material-design-lite

**Comment by rafaelvaloto** [comment]
The error occurs because the plug -in version must be `fxp / composer -asset- plugin: ~ 1.0.3 `. If you can fix please .

**Comment by rafaelvaloto** [comment]
The error occurs because the plug -in version must be fxp / composer -asset- plugin: ~ 1.0.3. If you can fix please .

**Comment by rafaelvaloto** [comment]
The error occurs because the plug -in version must be `fxp / composer -asset- plugin: ~ 1.0.3` . If you can fix please .

**Comment by rafaelvaloto** [comment]
Resolved in release v1.0.2
